<%-
  emailaddr = File.read(File.expand_path('~/ondemand/oidc_email.txt')).strip rescue ''
-%>
support_ticket:
  description: |
    Submit a support request for Eureka Open OnDemand. Include steps to reproduce,
    error text, and optionally screenshots/log snippets.

  attachments:
    max_items: 4
    max_size: 6291456

  email:
    from: <%= emailaddr.inspect %>
    to: "rschsppt+eureka@ualberta.ca"
    delivery_method: "smtp"
    delivery_settings:
      address: "smtp.ualberta.ca"
      port: 25
      domain: "ualberta.ca"
      enable_starttls_auto: true
      open_timeout: 15
      read_timeout: 15
