# AUTOGENERATED: DO NOT EDIT MANUALLY
# Sample / dev fallback when gen_gpu_rb.sh has not run (e.g. off-cluster). Replace via:
#   sudo /opt/ood/cron/gen_gpu_rb.sh
module CustomGPUInfo
  def self.gpu_types
    [
      "l40s",
    ]
  end
  def self.gpu_name_mappings
    {
      "l40s" => "NVIDIA L40S (full)",
    }
  end
  def self.gpu_max_counts
    {
      "l40s" => 4,
    }
  end
  def self.gpu_sharing_available
    false
  end
  def self.slices_per_gpu
    nil
  end
end
